name: Action Workflow

on: [push]

jobs:
    run-github-actions:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: action/checkout@v1
        - name: List file after
          run: |
            pwd
            ls -a
       